apiVersion: apps/v1
kind: Deployment
metadata:
  name: javacode
spec:
  replicas: 3
  selector:
    matchLabels:
      app: javacode
  template:
    metadata:
      labels:
        app: javacode
    spec:
      containers:
        - name: springboot
          image: rkeram1/javacode
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: javacode
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: javacode
